function edited = ManualSettings(manualDetector, varargin)
    handles.detector = manualDetector;
    
    handles.figure = dialog(...
        'Units', 'points', ...
        'Name', 'Manual Settings', ...
        'Position', [100, 100, 410, 116], ...
        'Visible', 'off', ...
        'WindowKeyPressFcn', @(hObject, eventdata)editManualKeyPress(hObject, eventdata, guidata(hObject)), ...
        'Tag', 'figure');
    
    % Add a field for setting the feature type
    uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12, ...
        'HorizontalAlignment', 'right', ...
        'Position', [10 80 180 18], ...
        'String',  'Type of feature to add:', ...
        'Style', 'text');
    handles.typeEdit = uicontrol(...
        'Parent', handles.figure, ...
        'Units', 'points', ...
        'FontSize', 12, ...
        'HorizontalAlignment', 'left', ...
        'Position', [200 80 200 26], ...
        'String',  handles.detector.featureType,...
        'Style', 'edit', ...
        'Tag', 'typeEdit');
    
    % Add a field for setting the hot key
    uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12, ...
        'HorizontalAlignment', 'right', ...
        'Position', [10 50 180 18], ...
        'String',  'Key to press:', ...
        'Style', 'text');
    handles.hotKeyEdit = uicontrol(...
        'Parent', handles.figure, ...
        'Units', 'points', ...
        'FontSize', 12, ...
        'HorizontalAlignment', 'left', ...
        'Position', [200 50 20 26], ...
        'String',  handles.detector.hotKey,...
        'Style', 'edit', ...
        'Tag', 'hotKeyEdit');
    
    handles.cancelButton = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'Callback', @(hObject,eventdata)cancelEditSettings(hObject,eventdata,guidata(hObject)), ...
        'Position', [410 - 10 - 56 - 10 - 56 10 56 20], ...
        'String', 'Cancel', ...
        'Tag', 'cancelButton');
    
    handles.saveButton = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'Callback', @(hObject,eventdata)saveEditSettings(hObject,eventdata,guidata(hObject)), ...
        'Position', [410 - 10 - 56 10 56 20], ...
        'String', 'Save', ...
        'Tag', 'saveButton');
    
    movegui(handles.figure, 'center');
    set(handles.figure, 'Visible', 'on');
    
    guidata(handles.figure, handles);
    
    % Wait for the user to cancel or save.
    uiwait;
    
    if ishandle(handles.figure)
        handles = guidata(handles.figure);
        edited = handles.edited;
        close(handles.figure);
    else
        edited = false;
    end
end


function editManualKeyPress(hObject, eventdata, handles)
    if strcmp(eventdata.Key, 'return')
        saveEditSettings(hObject, eventdata, handles);
    elseif strcmp(eventdata.Key, 'escape')
        cancelEditSettings(hObject, eventdata, handles);
    end
end


function cancelEditSettings(~, ~, handles)
    handles.edited = false;
    guidata(handles.figure, handles);
    uiresume;
end


function saveEditSettings(~, ~, handles)
    handles.detector.hotKey = get(handles.hotKeyEdit, 'String');
    handles.detector.featureType = get(handles.typeEdit, 'String');
    handles.edited = true;
    guidata(handles.figure, handles);
    uiresume;
end
